---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Tendencias temporales de las personas que declararon cambiar de residencia como medida de protección contra la delincuencia.

### Encuesta Nacional de Victimización y Percepción sobre la Pública (`ENVIPE`)  

<!-- badges: start -->
<!-- badges: end -->

Este repositorio contiene un análisis de las tendencias temporales de las personas que declararon haber cambiado de residencia como medida de protección contra la delincuencia, utilizando datos de la Encuesta Nacional de Victimización y Percepción sobre la Seguridad Pública (`ENVIPE`).

## Objetivo del Análisis

El objetivo principal es identificar las tendencias a lo largo del tiempo de los desplazamientos internos motivados por razones de seguridad y explorar los patrones subyacentes que pueden ayudar a comprender mejor este fenómeno.

Además, el análisis enfatiza la importancia de:

- **Muestreo complejo**: Verificar la representatividad de las encuestas es fundamental para garantizar la validez de los resultados. La ENVIPE utiliza diseños de muestrales que consideran factores como estratos y conglomerados.   
- **Datos representativos**: Usar correctamente los pesos muestrales para asegurar que las estimaciones reflejen con precisión las características de la población objetivo. Ignorar estas consideraciones puede llevar a resultados sesgados y decisiones mal informadas.   

## Contenido del Repositorio

- **Datos**: Instrucciones para acceder y preparar los datos de la ENVIPE, incluyendo información sobre las variables relevantes para el análisis de migración.
- **Resultados**: Gráficas y tablas que resumen los hallazgos clave.
- **Documentación**: Información técnica sobre la ENVIPE y referencias adicionales.

## Importancia del Muestreo Complejo

La ENVIPE utiliza un diseño de muestreo probabilistico, trietápico, estratificado y por conglomerados. Esto significa que:

- Los pesos de muestreo asignan una importancia relativa a cada observación para asegurar que las estimaciones sean representativas.
- La ignorancia de estas estructuras puede subestimar o sobrestimar la variabilidad de las estimaciones, resultando en errores en la interpretación de los resultados.

El uso adecuado de herramientas estadísticas que soporten el muestreo complejo, como las funciones del paquete `survey` en `R` o bien en otro paquete estadístico, es crucial para garantizar la validez de los análisis.  

## Consecuencias de Usar Datos No Representativos

El uso de datos no representativos puede tener consecuencias graves, entre ellas:

1. **Estimaciones sesgadas**: Los resultados pueden no reflejar la realidad de la población general, llevando a una comprensión errónea del fenómeno.
2. **Decisiones mal informadas**: Políticas basadas en datos sesgados podrían no abordar adecuadamente las necesidades de las personas afectadas.
3. **Pérdida de confianza**: Las decisiones basadas en datos incorrectos pueden erosionar la confianza en las instituciones y procesos que las sustentan.

## Requisitos y Herramientas

Para replicar el análisis, necesitará:

- **Software**: R (versión 4.0 o superior).
-  **Paquetes**: `tidyverse`, `survey`, `ggplot2`, entre otros.
- **Datos**: Archivos de microdatos de la ENVIPE disponibles en el [INEGI](https://www.inegi.org.mx).

En el siguiente script se muestran las tendencias temporales de las estimaciones sobre personas que han tenido que cambiar su residencia por motivos de delincuencia.   

**Enlace:** https://dvillasanao.github.io/MC_ENVIPE/Output/MC_ENVIPE.html 